# Generated by Django 3.2.3 on 2021-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='userHandle',
            field=models.CharField(default='adminOP', max_length=50),
        ),
        migrations.AddField(
            model_name='tweet',
            name='userName',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
